# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 050d09309404e16e892ff000c5b4aed1e601a05391315d28a1baae020a8bca09c25f32d72a7e68f94ad026cc6ccefa8f0dceba7ffbd051e04c70bfbfb0b81279

test:
  secret_key_base: 0c75ec29b341c38be08110ed76441da8ad6c52c528779f1272a1c66c901c6d79dce968f27cb53bc98a696c6efb87c7658f092f3a3f46d5e7cbd3ad76f6d7d6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
